homework done
KlimovDima/array2 pull request #1
Opened 2023-03-22 20:41 UTC by KlimovDima

2023-03-22 23:33 UTC, safgbad requested changes

2023-03-22 23:33 UTC, safgbad commented on src/Main.java
> +        }
все элементы массива надо было просуммировать и вывести лишь только общую сумму

2023-03-22 23:33 UTC, safgbad commented on src/Main.java
> +        int minSpending = Integer.MAX_VALUE;
&#128077;

2023-03-22 23:33 UTC, safgbad commented on src/Main.java
> +        System.out.println(mean);
а зачем -1?

2023-03-23 20:41 UTC, KlimovDima commented on src/Main.java
> +        }
Ну да, перепутал)

2023-03-23 20:41 UTC, KlimovDima commented on src/Main.java
> +        System.out.println(mean);
А не знаю

2023-03-23 20:42 UTC, safgbad approved these changes

2023-03-23 21:10 UTC, merged